spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=my_rewards
    username: my_rewards
    password: Serole@123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
    generate-ddl: false

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always
logging:
  level:
    org:
      springframework:
        security: INFO
server:
  port: 8081
